<template><h1 id="标准api" tabindex="-1"><a class="header-anchor" href="#标准api" aria-hidden="true">#</a> 标准API</h1>
<h2 id="全局变量" tabindex="-1"><a class="header-anchor" href="#全局变量" aria-hidden="true">#</a> 全局变量</h2>
<h3 id="env-dev" tabindex="-1"><a class="header-anchor" href="#env-dev" aria-hidden="true">#</a> env_dev</h3>
<h3 id="setting" tabindex="-1"><a class="header-anchor" href="#setting" aria-hidden="true">#</a> setting</h3>
<h2 id="全局api" tabindex="-1"><a class="header-anchor" href="#全局api" aria-hidden="true">#</a> 全局API</h2>
<h3 id="util" tabindex="-1"><a class="header-anchor" href="#util" aria-hidden="true">#</a> util</h3>
<h4 id="refreshvuedata" tabindex="-1"><a class="header-anchor" href="#refreshvuedata" aria-hidden="true">#</a> refreshVueData</h4>
<h3 id="array" tabindex="-1"><a class="header-anchor" href="#array" aria-hidden="true">#</a> array</h3>
<h3 id="url" tabindex="-1"><a class="header-anchor" href="#url" aria-hidden="true">#</a> url</h3>
<h3 id="validate" tabindex="-1"><a class="header-anchor" href="#validate" aria-hidden="true">#</a> validate</h3>
<h3 id="http" tabindex="-1"><a class="header-anchor" href="#http" aria-hidden="true">#</a> http</h3>
<h3 id="broadcast" tabindex="-1"><a class="header-anchor" href="#broadcast" aria-hidden="true">#</a> broadcast</h3>
<h3 id="module" tabindex="-1"><a class="header-anchor" href="#module" aria-hidden="true">#</a> module</h3>
<h3 id="express" tabindex="-1"><a class="header-anchor" href="#express" aria-hidden="true">#</a> express</h3>
<h3 id="cachepool" tabindex="-1"><a class="header-anchor" href="#cachepool" aria-hidden="true">#</a> cachePool</h3>
<h3 id="app" tabindex="-1"><a class="header-anchor" href="#app" aria-hidden="true">#</a> app</h3>
<h3 id="user" tabindex="-1"><a class="header-anchor" href="#user" aria-hidden="true">#</a> user</h3>
<h3 id="theme" tabindex="-1"><a class="header-anchor" href="#theme" aria-hidden="true">#</a> theme</h3>
<h3 id="watermark" tabindex="-1"><a class="header-anchor" href="#watermark" aria-hidden="true">#</a> watermark</h3>
<h3 id="message" tabindex="-1"><a class="header-anchor" href="#message" aria-hidden="true">#</a> message</h3>
<h3 id="develop" tabindex="-1"><a class="header-anchor" href="#develop" aria-hidden="true">#</a> develop</h3>
<h2 id="兼容api" tabindex="-1"><a class="header-anchor" href="#兼容api" aria-hidden="true">#</a> 兼容API</h2>
</template>
